# Generated by Django 4.2.5 on 2024-03-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ToekomstPiano", "0002_alter_userregistration_date_of_birth_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThemePreference",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                (
                    "theme_preference",
                    models.CharField(
                        choices=[("light", "Light"), ("dark", "Dark")], max_length=5
                    ),
                ),
            ],
        ),
    ]
