# Generated by Django 4.2.5 on 2024-04-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ToekomstPiano", "0003_themepreference"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
    ]
