# Generated by Django 4.2.5 on 2024-04-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ToekomstPiano", "0004_contactmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_id", models.CharField(max_length=100)),
                ("order_id", models.CharField(max_length=100)),
                ("signature", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
