# Generated by Django 4.2.5 on 2024-04-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ToekomstPiano", "0005_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperienceForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("designing_experience", models.CharField(max_length=255)),
                ("additional_details", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ProfileSettingsForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mobile_number", models.CharField(max_length=20)),
                ("address_line_1", models.CharField(max_length=255)),
                ("address_line_2", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=100)),
                ("state_region", models.CharField(max_length=100)),
            ],
        ),
    ]
